params:
  kaoqin:
     #考勤表存储位置
     filepath: D:\account
     #参与考勤人员的姓名
     name: 闫明;刘晓宇;张金梁;王思铭;赵志刚;周志伟;刘春旭;张振环;潘晨;常若男;胡文达;董博宇;王孟然
     #允许迟到的次数
     freeBeLateTimes: 3
     #一般迟到次数的上限
     smallBeLateTimes: 6
     #一般迟到扣考勤天数
     freeBlateDays: 0.5
     #旷工扣考勤天数
     smallBlateDays: 1
     #加班折算调休时长比例
     overtimeRate: 0.5
     #旷工迟到起始时间
     beLateLimitMinute: 30
     #特殊工作日和假日
     specialworkday: 2021-01-01:0;2021-02-07:1;2021-02-11:0;2021-02-12:0;2021-02-15:0;2021-02-16:0;2021-02-17:0;2021-02-20:1;2021-04-05:0;2021-04-25:1;2021-05-03:0;2021-05-04:0;2021-05-05:0;2021-05-08:1;2021-06-14:0;2021-09-18:1;2021-09-20:0;2021-09-21:0;2021-09-26:1;2021-10-01:0;2021-10-04:0;2021-10-05:0;2021-10-06:0;2021-10-07:0;2021-10-09:1
     #标准上班时间,时间中间的冒号要换成分号,不然程序里取到的数据会转换格式
     standardClockIn: 9;00
     #标准下班时间,时间中间的冒号要换成分号,不然程序里取到的数据会转换格式
     standardClockOut: 18;00
     #晚餐补助开始时间,时间中间的冒号要换成分号,不然程序里取到的数据会转换格式
     subsidyStartTime: 19;00
     #加班累计开始时间,时间中间的冒号要换成分号,不然程序里取到的数据会转换格式
     overtimeStartTime: 19;00

server:
  port: 8081
  name: KaoQin

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/reinsdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: reins
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.kaoqin.po  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

